# Generated by Django 3.2.4 on 2021-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='generator_script_path',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='solver_script_path',
        ),
        migrations.AddField(
            model_name='challenge',
            name='generator_script_import_statement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solver_script_import_statement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='assignment_modal_template_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image_src_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
